# dev environment
name: thesis
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - torchtext
  - cudatoolkit=11.1
  - jupyter
  - notebook
  - rdkit
  - pytest
  - dvc
  - dvc-s3
  - tensorboard
  - pip
  - pip:
      - transformers
      - pytorch-lightning
      - torchmetrics
      - datasets
      - tensorflow~=2.4
      - deepchem
      - wget
      - mlflow
      - jsonargparse[signatures] # needed for lightning cli
      - optuna
