name: thesis
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - torchtext
  - cudatoolkit=11.1
  - jupyter
  - notebook
  - rdkit
  - pytest
  - pip
  - pip:
      - transformers
      - pytorch-lightning
      - datasets
      - tensorflow~=2.4
      - deepchem
